name: Release
on:
  release:
    types:
      - published
jobs:
  validate-node:
    name: 'Validate'
    uses: curium-rocks/flows/.github/workflows/node-ts.yml@main
    secrets:
      SONARQUBE_KEY: ${{ secrets.SONARQUBE_KEY }}
  publish-to-npm:
    environment: npm
    runs-on: ubuntu-latest
    needs:
      - validate-node
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN }}
